### ISSUE TITLE
SoftwareDistributionTask just waits for wuauserv to stop

### ISSUE THREAD

**Issue by B00ze64** [farag2/Sophia-Script-for-Windows#328] opened 2022-02-01 04:33 UTC
### Prerequisites

- [X] Verify that this is not a Windows issue;
- [ ] Refer to the [**Before running**](https://github.com/farag2/Sophia-Script-for-Windows#fire-before-running-fire).
- [ ] Refer to the [**How to use**](https://github.com/farag2/Sophia-Script-for-Windows#how-to-use).
- [ ] If you issue concerns the Wrapper, please mention @BenchTweakGaming in issue

### Steps to reproduce

Good day.

As far as I can tell, this just waits for the service to stop, but it never sends a stop command so it just sits there...
Should we not see a Stop-Service somewhere? (and a [re]start later on?)
```ps1
$SoftwareDistributionTask = @"
(Get-Service -Name wuauserv).WaitForStatus('Stopped', '01:00:00')
Get-ChildItem -Path `$env:SystemRoot\SoftwareDistribution\Download -Recurse -Force | Remove-Item -Recurse -Force
[...]
$Action = New-ScheduledTaskAction -Execute powershell.exe -Argument "-WindowStyle Hidden -Command $SoftwareDistributionTask"
```

**Comment by farag2** [comment] 2022-02-01 06:03
Hi. No, this is by design. :) Let the service wait until it stops by itself. What if we stop when it will be installing a new update? That's why we have to wait for about an hour. It's OK, as the practice has shown. Have been using it as is for 2 years in every my PC.

**Closed by farag2** 2022-02-01 06:03 UTC

**Comment by B00ze64** [comment] 2022-02-02 01:10
Oh, so it stops regularly? Lol, and I've gone and modified my task already to include stop/starting the service. Time to delete the task and use your default ;-) Thanks.

**Comment by farag2** [comment] 2022-02-02 03:22
Yeah, it stops after about 15 minutes when everything iHe-hes installed. He-he. :)
